# Dataset : https://www.kaggle.com/datasets/moro146/supermarket-eda

# Imports

In [4]:
!pip install numpy pandas

Requirement already satisfied: numpy in c:\users\el-wattaneya\anaconda3\lib\site-packages (1.22.4)
Requirement already satisfied: pandas in c:\users\el-wattaneya\anaconda3\lib\site-packages (2.0.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\el-wattaneya\anaconda3\lib\site-packages (from pandas) (2021.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\el-wattaneya\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.1 in c:\users\el-wattaneya\anaconda3\lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in c:\users\el-wattaneya\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)

In [5]:
import numpy as np
import pandas as pd

# Q1 
* ## Load the Data
* ## Display the First 5 Entries
* ## Display the Last 5 Entries
* ## View Dataset Information
* ## Generate Descriptive Statistics (Numeric and Categorical Data)

In [26]:
data = pd.read_csv("supermarket.csv")

In [27]:
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [28]:
data.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.798
9796,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.368
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.188
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.376
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.384

In [29]:
data.info

<bound method DataFrame.info of       Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
0          1  CA-2017-152156  08/11/2017  11/11/2017    Second Class
1          2  CA-2017-152156  08/11/2017  11/11/2017    Second Class
2          3  CA-2017-138688  12/06/2017  16/06/2017    Second Class
3          4  US-2016-108966  11/10/2016  18/10/2016  Standard Class
4          5  US-2016-108966  11/10/2016  18/10/2016  Standard Class
...      ...             ...         ...         ...             ...
9795    9796  CA-2017-125920  21/05/2017  28/05/2017  Standard Class
9796    9797  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9797    9798  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9798    9799  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9799    9800  CA-2016-128608  12/01/2016  17/01/2016  Standard Class

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson
1       CG-12520       Claire Gute   Consumer  United States        Henderson
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
...          ...               ...        ...            ...              ...
9795    SH-19975     Sally Hughsby  Corporate  United States          Chicago
9796    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9797    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9798    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9799    CS-12490  Cindy Schnelling  Corporate  United States           Toledo

           State  Postal Code   Region       Product ID         Category  \
0       Kentucky      42420.0    South  FUR-BO-10001798        Furniture
1       Kentucky      42420.0    South  FUR-CH-10000454        Furniture
2     California      90036.0     West  OFF-LA-10000240  Office Supplies
3        Florida      33311.0    South  FUR-TA-10000577        Furniture
4        Florida      33311.0    South  OFF-ST-10000760  Office Supplies
...          ...          ...      ...              ...              ...
9795    Illinois      60610.0  Central  OFF-BI-10003429  Office Supplies
9796        Ohio      43615.0     East  OFF-AR-10001374  Office Supplies
9797        Ohio      43615.0     East  TEC-PH-10004977       Technology
9798        Ohio      43615.0     East  TEC-PH-10000912       Technology
9799        Ohio      43615.0     East  TEC-AC-10000487       Technology

     Sub-Category                                       Product Name     Sales
0       Bookcases                  Bush Somerset Collection Bookcase  261.9600
1          Chairs  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400
2          Labels  Self-Adhesive Address Labels for Typewriters b...   14.6200
3          Tables      Bretford CR4500 Series Slim Rectangular Table  957.5775
4         Storage                     Eldon Fold 'N Roll Cart System   22.3680
...           ...                                                ...       ...
9795      Binders  Cardinal HOLDit! Binder Insert Strips,Extra St...    3.7980
9796          Art           BIC Brite Liner Highlighters, Chisel Tip   10.3680
9797       Phones                                        GE 30524EE4  235.1880
9798       Phones           Anker 24W Portable Micro USB Car Charger   26.3760
9799  Accessories                SanDisk Cruzer 4 GB USB Flash Drive   10.3840

[9800 rows x 18 columns]>

In [30]:
data.describe()

            Row ID   Postal Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

In [31]:
data.describe(include='object')

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Product ID,Category,Sub-Category,Product Name
count,9800,9800,9800,9800,9800,9800,9800,9800,9800,9800,9800,9800,9800,9800,9800
unique,4922,1230,1326,4,793,793,3,1,529,49,4,1861,3,17,1849
top,CA-2018-100111,05/09/2017,26/09/2018,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,California,West,OFF-PA-10001970,Office Supplies,Binders,Staple envelope
freq,14,38,34,5859,35,35,5101,9800,891,1946,3140,19,5909,1492,47

# Q2
* ## Identify and Resolve Duplicate Entries
* ## Detect and Handle Missing Values

In [32]:
data.duplicated().sum()

0

In [33]:
data=data.drop_duplicates()

In [34]:
data.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [37]:
num_col = data.select_dtypes(include=np.number).columns
data[num_col] = data[num_col].fillna(data[num_col].median())

string_col = data.select_dtypes(include='object').columns
data[string_col] = data[string_col].fillna( data[string_col] .mode().iloc[0])

# Q3
* ## Make (Row ID as an index)

In [46]:
data.columns

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code',
       'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name',
       'Sales'],
      dtype='object')

In [68]:
#data.set_index("Row ID" , inplace=True)

# Q4
* ## Using aggregate function to calculate (Max, Min, Mean) of sales column

In [48]:
data['Sales'].agg(['max', 'min', 'mean'])

max     22638.480000
min         0.444000
mean      230.769059
Name: Sales, dtype: float64

# Q5
* ## What is the most Category and sub-category saled ?
* ## And Make a Pivot table to Calculate the mean for each Category 
* ## Save the pivot table as an excel sheet

In [54]:
data['Category'].value_counts()

Category
Office Supplies    5909
Furniture          2078
Technology         1813
Name: count, dtype: int64

In [55]:
data['Category'].value_counts().idxmax()

'Office Supplies'

In [58]:
data['Sub-Category'].value_counts().idxmax()

'Binders'

In [ ]:
pivot_table=pd.pivot_table(
    data , 
    values='Sales',
    index='Category',
    aggfunc='mean'
)
pivot_table

                      Sales
Category
Furniture        350.653790
Office Supplies  119.381001
Technology       456.401474

# Q6 
* ## Replace full country names with their abbreviations (e.g., "United States" becomes "US") and rename the column to "The Country.

In [61]:
country_map = {
    "United States":"US",
    "Canada":"CA",
    "Mexico":"MX"
}

In [62]:
data['Country']=data['Country'].replace(country_map)

In [64]:
data.rename(
    columns = {"Country":"The Country"},
    inplace=True
)



data.head

<bound method NDFrame.head of               Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
Row ID
1       CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520
2       CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520
3       CA-2017-138688  12/06/2017  16/06/2017    Second Class    DV-13045
4       US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335
5       US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335
...                ...         ...         ...             ...         ...
9796    CA-2017-125920  21/05/2017  28/05/2017  Standard Class    SH-19975
9797    CA-2016-128608  12/01/2016  17/01/2016  Standard Class    CS-12490
9798    CA-2016-128608  12/01/2016  17/01/2016  Standard Class    CS-12490
9799    CA-2016-128608  12/01/2016  17/01/2016  Standard Class    CS-12490
9800    CA-2016-128608  12/01/2016  17/01/2016  Standard Class    CS-12490

           Customer Name    Segment The Country             City       State  \
Row ID
1            Claire Gute   Consumer          US        Henderson    Kentucky
2            Claire Gute   Consumer          US        Henderson    Kentucky
3        Darrin Van Huff  Corporate          US      Los Angeles  California
4         Sean O'Donnell   Consumer          US  Fort Lauderdale     Florida
5         Sean O'Donnell   Consumer          US  Fort Lauderdale     Florida
...                  ...        ...         ...              ...         ...
9796       Sally Hughsby  Corporate          US          Chicago    Illinois
9797    Cindy Schnelling  Corporate          US           Toledo        Ohio
9798    Cindy Schnelling  Corporate          US           Toledo        Ohio
9799    Cindy Schnelling  Corporate          US           Toledo        Ohio
9800    Cindy Schnelling  Corporate          US           Toledo        Ohio

        Postal Code   Region       Product ID         Category Sub-Category  \
Row ID
1           42420.0    South  FUR-BO-10001798        Furniture    Bookcases
2           42420.0    South  FUR-CH-10000454        Furniture       Chairs
3           90036.0     West  OFF-LA-10000240  Office Supplies       Labels
4           33311.0    South  FUR-TA-10000577        Furniture       Tables
5           33311.0    South  OFF-ST-10000760  Office Supplies      Storage
...             ...      ...              ...              ...          ...
9796        60610.0  Central  OFF-BI-10003429  Office Supplies      Binders
9797        43615.0     East  OFF-AR-10001374  Office Supplies          Art
9798        43615.0     East  TEC-PH-10004977       Technology       Phones
9799        43615.0     East  TEC-PH-10000912       Technology       Phones
9800        43615.0     East  TEC-AC-10000487       Technology  Accessories

                                             Product Name     Sales
Row ID
1                       Bush Somerset Collection Bookcase  261.9600
2       Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400
3       Self-Adhesive Address Labels for Typewriters b...   14.6200
4           Bretford CR4500 Series Slim Rectangular Table  957.5775
5                          Eldon Fold 'N Roll Cart System   22.3680
...                                                   ...       ...
9796    Cardinal HOLDit! Binder Insert Strips,Extra St...    3.7980
9797             BIC Brite Liner Highlighters, Chisel Tip   10.3680
9798                                          GE 30524EE4  235.1880
9799             Anker 24W Portable Micro USB Car Charger   26.3760
9800                  SanDisk Cruzer 4 GB USB Flash Drive   10.3840

[9800 rows x 17 columns]>

# Q7
* ## Calculate the number of shipping days between the "Order Date" and "Ship Date" columns
* ## And calculate the maximum shipping days and the city of it

In [70]:
data.columns

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'The Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales'],
      dtype='object')

In [74]:
data['Order Date']=pd.to_datetime(
    data["Order Date"] ,
    dayfirst=True
)

data['Ship Date'] =pd.to_datetime(
    data['Ship Date'] , 
    dayfirst=True
)

In [77]:
data['Shipping Days'] = (data['Ship Date'] - data['Order Date']).dt.days

In [79]:
max_days = data['Shipping Days'].max()

max_days

7

In [86]:
city=data.loc[data['Shipping Days'].idxmax(),'City']

city

'Fort Lauderdale'

# Q8 (NumPy)
* ## Import the numpy library
* ## Convert the "Sales" column to a 1D NumPy array
* ## Calculate the sum, mean, and standard deviation of this array using NumPy functions

In [91]:
import numpy as np

sales_array = data['Sales'].to_numpy()

sales_array

array([261.96 , 731.94 ,  14.62 , ..., 235.188,  26.376,  10.384])

In [92]:
print("sum = " ,np.sum(sales_array))
print("Mean = " ,np.mean(sales_array))
print("Std = " ,np.std(sales_array))

sum =  2261536.7827000003
Mean =  230.7690594591837
Std =  626.619901988719

# Q9 (NumPy)
* ## Filter the Sales NumPy array to find all sales greater than 1000
* ## How many such high-value sales are there?

In [94]:
high_sales = sales_array[
    sales_array >1000
]

high_sales

array([ 1706.184 ,  1044.63  ,  3083.43  ,  1097.544 ,  1029.95  ,
        1113.024 ,  1951.84  ,  8159.952 ,  1740.06  ,  1188.    ,
        2001.86  ,  1503.25  ,  3347.37  ,  3059.982 ,  2519.958 ,
        1114.4   ,  1038.84  ,  1082.48  ,  3991.98  ,  4355.168 ,
        1043.92  ,  1023.936 ,  1488.424 ,  1799.97  ,  2396.2656,
        1199.976 ,  1004.024 ,  1336.829 ,  1007.979 ,  1272.63  ,
        2735.952 ,  6354.95  ,  2999.95  ,  1126.02  ,  1121.568 ,
        1295.78  ,  1335.68  ,  1199.976 ,  1049.2   ,  7999.98  ,
        1652.94  ,  1199.976 ,  1363.96  ,  1983.968 ,  1298.55  ,
        1399.93  ,  1228.465 ,  1141.47  ,  1242.9   ,  1199.8   ,
        1928.78  ,  1114.272 ,  1007.232 ,  2065.32  ,  3059.982 ,
        1166.92  ,  2715.93  ,  2309.65  ,  1090.782 ,  1618.37  ,
        1267.53  ,  1379.92  ,  1363.96  ,  1113.504 ,  1106.91  ,
        4899.93  ,  1067.94  ,  2244.48  ,  1322.93  ,  1088.792 ,
        1931.958 ,  3610.848 ,  1141.938 ,  1704.56  ,  1099.96  ,
        1089.75  ,  1819.86  ,  2453.43  ,  1979.928 ,  3040.    ,
        1024.716 ,  1212.848 ,  1004.976 ,  1669.6   ,  1573.488 ,
        1044.63  ,  1217.568 ,  1000.02  ,  1265.85  ,  1006.056 ,
        1247.64  ,  3149.93  ,  1018.104 ,  1931.04  ,  1702.12  ,
        1048.35  ,  1718.4   ,  2807.84  ,  4663.736 ,  2575.944 ,
        1441.3   ,  1127.976 ,  1439.92  ,  1439.982 ,  1245.86  ,
        1793.98  ,  1282.41  ,  1394.95  ,  1439.976 ,  1024.38  ,
        1606.23  ,  1586.69  ,  1295.84  ,  3999.95  ,  1454.49  ,
        1145.6   ,  1016.792 ,  1212.96  ,  1119.984 ,  1399.93  ,
        1552.831 ,  1579.746 ,  1071.576 ,  1619.91  ,  1115.91  ,
        2396.4   ,  1101.48  ,  1322.352 ,  1003.62  ,  1137.75  ,
        4548.81  ,  8187.65  ,  1117.92  ,  1801.632 ,  1348.704 ,
        1879.96  ,  1406.86  ,  2665.62  ,  1399.944 ,  1349.85  ,
        1218.735 , 11199.968 ,  2399.6   ,  1292.94  ,  1979.89  ,
        1325.85  , 22638.48  ,  1919.976 ,  1447.65  ,  1924.16  ,
        1075.088 ,  1088.76  ,  1139.92  ,  2690.97  ,  1603.136 ,
        1628.82  ,  1013.488 ,  1633.188 ,  1526.56  ,  1267.65  ,
        2549.985 ,  2054.272 ,  1022.97  ,  2799.96  ,  2934.33  ,
        1123.92  ,  1036.624 ,  2025.36  ,  1799.994 ,  1633.14  ,
        3359.952 ,  4164.05  ,  1704.89  ,  1919.976 ,  1287.45  ,
        1799.75  ,  1091.168 ,  1408.1   ,  2504.74  ,  1421.664 ,
        1202.94  ,  1577.94  ,  2395.2   ,  1687.8   ,  2430.08  ,
        1169.694 ,  1665.62  ,  1443.96  ,  2060.744 ,  1259.93  ,
        1013.832 ,  2003.52  ,  1085.42  ,  1359.96  ,  1056.86  ,
        1458.65  ,  1049.97  ,  1684.752 ,  1424.9   ,  2799.96  ,
        2591.56  ,  1801.632 ,  3080.    ,  9449.95  ,  1219.96  ,
        2624.985 ,  1575.14  , 10499.97  ,  1604.9   ,  4799.984 ,
        1049.2   ,  9099.93  ,  1103.97  ,  4367.896 ,  1598.058 ,
        1487.04  ,  1259.97  ,  1805.88  ,  1279.165 ,  1332.496 ,
        1347.52  ,  2879.952 ,  1599.92  ,  1117.92  ,  1199.976 ,
        1793.98  ,  2404.704 ,  2249.91  ,  1126.02  ,  1263.3   ,
        1117.92  ,  1325.85  ,  1268.82  ,  1325.76  ,  1889.99  ,
        2321.9   ,  1502.376 ,  1352.3976,  1781.682 ,  2799.96  ,
        1317.492 ,  1214.85  ,  1001.584 ,  1367.84  ,  3504.9   ,
        1801.632 ,  1516.2   ,  3930.072 ,  2275.5   ,  1979.7   ,
        1525.188 ,  2314.116 ,  1025.88  ,  1649.95  ,  1640.7   ,
        1478.272 ,  1319.96  ,  2479.96  ,  1325.85  ,  2999.95  ,
        1496.16  ,  1040.8   ,  2348.82  ,  1256.22  ,  1325.76  ,
        1194.165 ,  1049.93  ,  2799.944 ,  1089.75  ,  1999.96  ,
        1448.82  ,  1158.12  ,  1395.54  ,  1487.976 ,  1133.35  ,
        1603.136 ,  1293.488 ,  4912.59  ,  4228.704 ,  2003.92  ,
        1099.5   ,  1215.92  ,  2357.488 ,  2548.56  ,  4158.912 ,
        1345.485 ,  1199.96  ,  2888.127 ,  1299.66  ,  2254.41  ,
        1474.802 ,  1537.074 ,  2279.96  ,  1198.33  ,  1690.04  ,
        1439.968 ,  2793.528 ,  1000.02  ,  1471.96  ,  1159.056 ,
        1737.18  ,  5199.96  ,  1039.992 ,  8399.976 ,  2079.4   ,
        1247.64  ,  5443.96  ,  1999.96  ,  2152.776 ,  4007.84  ,
        1522.638 ,  1049.44  ,  1007.944 ,  4164.05  ,  6999.96  ,
        1747.25  ,  1421.664 ,  1117.92  ,  1362.9   ,  3266.376 ,
       17499.95  ,  1640.7   ,  1059.12  ,  1565.88  ,  2887.056 ,
        1652.94  ,  2003.92  ,  1913.4   ,  2567.84  ,  2399.96  ,
        1001.584 ,  1403.92  ,  1158.12  ,  1261.33  ,  1012.68  ,
        1626.192 ,  1685.88  ,  1879.96  ,  2399.96  ,  1350.12  ,
        1319.8   ,  4416.174 ,  2541.98  ,  1279.968 ,  1856.19  ,
        1336.44  ,  1415.76  ,  1036.624 ,  1196.86  ,  1499.95  ,
        2573.82  ,  2249.91  ,  1053.164 ,  1889.946 ,  1399.98  ,
        1487.04  ,  2625.12  ,  3499.93  ,  1297.368 ,  1207.84  ,
        1299.99  ,  1352.032 ,  1548.99  ,  5399.91  ,  1687.8   ,
        3812.97  ,  1568.61  ,  1199.98  ,  1779.9   ,  1039.728 ,
        4499.985 ,  1497.666 ,  4535.976 ,  1184.72  ,  1871.88  ,
        1614.582 ,  3404.5   ,  2518.29  ,  1673.184 ,  1323.9   ,
        3357.6   ,  2973.32  ,  1079.976 , 13999.96  ,  2036.86  ,
        1252.704 ,  4643.8   ,  1369.764 ,  1266.86  ,  2803.92  ,
        2003.168 ,  2563.056 ,  1085.42  ,  1649.95  ,  2939.93  ,
        2154.9   ,  1679.96  ,  1554.936 ,  2678.94  ,  1035.8   ,
        8749.95  ,  1056.86  ,  1454.9   ,  1287.45  ,  1369.764 ,
        2104.55  ,  2239.936 ,  1287.45  ,  3050.376 ,  1270.99  ,
        1227.9984,  1128.39  ,  1294.75  ,  1799.97  ,  1217.568 ,
        5083.96  ,  1927.59  ,  2676.672 ,  1439.968 ,  1119.888 ,
        4899.93  ,  1875.258 ,  1793.98  ,  9892.74  ,  2621.322 ,
        1115.17  ,  1123.128 ,  1564.29  ,  4476.8   ,  1112.94  ,
        1473.1   ,  1432.    ,  1504.52  ,  1091.168 ,  4305.552 ,
        1577.94  ,  1079.316 ,  1676.88  ,  1349.91  ,  1591.02  ,
        1071.    ,  2803.92  ,  3785.292 ,  1212.96  ,  1099.96  ,
        2022.272 ,  1592.85  ,  1091.93  ,  1649.75  ,  1125.488 ,
        1079.85  ,  2033.584 ,  1628.82  ,  4297.644 ,  3406.664 ,
        3023.928 ,  1499.97  ,  1080.096 ,  4404.9   ,  1403.92  ,
        2177.584 ,  1023.332 ])

In [95]:
len(high_sales)

462

In [96]:
high_sales.size

462

# Q10 (NumPy)
* ## Create a NumPy array of 10 random integers between 1 and 100
* ## Reshape the array into a 2x5 matrix
* ## Multiply the entire matrix by 5

In [99]:
random_array =np.random.randint(
    1 , 
    101 , 
    10 
)

random_array

array([17, 58, 60, 62, 30, 96, 62, 88, 43, 57])

In [103]:
matrix =random_array.reshape( 2 , 5 )

matrix

array([[17, 58, 60, 62, 30],
       [96, 62, 88, 43, 57]])

In [104]:
matrix * 5

array([[ 85, 290, 300, 310, 150],
       [480, 310, 440, 215, 285]])